package com.nekomizus.combat;

import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.animal.Chicken;
import net.minecraft.world.entity.monster.Creeper;
import net.minecraft.world.level.block.Block;

import java.util.Map;

public class CombatXP {
    record MobXP(int XP) {}

    private static final Map<EntityType<?>, CombatXP.MobXP> COMBAT_XP = Map.ofEntries(
            Map.entry(EntityType.ALLAY, new MobXP(20)),
            Map.entry(EntityType.ARMADILLO, new MobXP(6)),
            Map.entry(EntityType.AXOLOTL, new MobXP(14)),
            Map.entry(EntityType.BAT, new MobXP(6)),
            Map.entry(EntityType.BEE, new MobXP(10)),
            Map.entry(EntityType.BLAZE, new MobXP(20)),
            Map.entry(EntityType.BOGGED, new MobXP(16)),
            Map.entry(EntityType.BREEZE, new MobXP(30)),
            Map.entry(EntityType.CAMEL, new MobXP(32)),
            Map.entry(EntityType.CAT, new MobXP(10)),
            Map.entry(EntityType.CAVE_SPIDER, new MobXP(12)),
            Map.entry(EntityType.CHICKEN, new MobXP(4)),
            Map.entry(EntityType.COD, new MobXP(3)),
            Map.entry(EntityType.COW, new MobXP(10)),
            Map.entry(EntityType.CREEPER, new MobXP(20)),
            Map.entry(EntityType.DOLPHIN, new MobXP(10)),
            Map.entry(EntityType.DONKEY, new MobXP(15)),
            Map.entry(EntityType.DROWNED, new MobXP(20)),
            Map.entry(EntityType.ELDER_GUARDIAN, new MobXP(80)),
            Map.entry(EntityType.ENDER_DRAGON, new MobXP(200)),
            Map.entry(EntityType.ENDERMAN, new MobXP(40)),
            Map.entry(EntityType.ENDERMITE, new MobXP(8)),
            Map.entry(EntityType.EVOKER, new MobXP(24)),
            Map.entry(EntityType.FOX, new MobXP(10)),
            Map.entry(EntityType.FROG, new MobXP(10)),
            Map.entry(EntityType.GHAST, new MobXP(10)),
            Map.entry(EntityType.GLOW_SQUID, new MobXP(10)),
            Map.entry(EntityType.GOAT, new MobXP(10)),
            Map.entry(EntityType.GUARDIAN, new MobXP(30)),
            Map.entry(EntityType.HOGLIN, new MobXP(40)),
            Map.entry(EntityType.HORSE, new MobXP(15)),
            Map.entry(EntityType.HUSK, new MobXP(20)),
            Map.entry(EntityType.IRON_GOLEM, new MobXP(100)),
            Map.entry(EntityType.ILLUSIONER, new MobXP(32)),
            Map.entry(EntityType.LLAMA, new MobXP(15)),
            Map.entry(EntityType.MAGMA_CUBE, new MobXP(16)),
            Map.entry(EntityType.MOOSHROOM, new MobXP(10)),
            Map.entry(EntityType.MULE, new MobXP(80)),
            Map.entry(EntityType.OCELOT, new MobXP(80)),
            Map.entry(EntityType.PANDA, new MobXP(80)),
            Map.entry(EntityType.PARROT, new MobXP(80)),
            Map.entry(EntityType.PHANTOM, new MobXP(80)),
            Map.entry(EntityType.PIG, new MobXP(80)),
            Map.entry(EntityType.PIGLIN, new MobXP(80)),
            Map.entry(EntityType.PIGLIN_BRUTE, new MobXP(80)),
            Map.entry(EntityType.PILLAGER, new MobXP(80)),
            Map.entry(EntityType.POLAR_BEAR, new MobXP(80)),
            Map.entry(EntityType.PUFFERFISH, new MobXP(80)),
            Map.entry(EntityType.RABBIT, new MobXP(80)),
            Map.entry(EntityType.RAVAGER, new MobXP(80)),
            Map.entry(EntityType.SALMON, new MobXP(80)),
            Map.entry(EntityType.SHEEP, new MobXP(80)),
            Map.entry(EntityType.SHULKER, new MobXP(80)),
            Map.entry(EntityType.SILVERFISH, new MobXP(80)),
            Map.entry(EntityType.SKELETON, new MobXP(80)),
            Map.entry(EntityType.SKELETON_HORSE, new MobXP(80)),
            Map.entry(EntityType.SLIME, new MobXP(80)),
            Map.entry(EntityType.SNIFFER, new MobXP(80)),
            Map.entry(EntityType.SNOW_GOLEM, new MobXP(80)),
            Map.entry(EntityType.SPIDER, new MobXP(80)),
            Map.entry(EntityType.STRAY, new MobXP(80)),
            Map.entry(EntityType.SQUID, new MobXP(80)),
            Map.entry(EntityType.STRIDER, new MobXP(80)),
            Map.entry(EntityType.TADPOLE, new MobXP(80)),
            Map.entry(EntityType.TRADER_LLAMA, new MobXP(80)),
            Map.entry(EntityType.TROPICAL_FISH, new MobXP(80)),
            Map.entry(EntityType.TURTLE, new MobXP(80)),
            Map.entry(EntityType.VEX, new MobXP(80)),
            Map.entry(EntityType.VILLAGER, new MobXP(80)),
            Map.entry(EntityType.VINDICATOR, new MobXP(80)),
            Map.entry(EntityType.WANDERING_TRADER, new MobXP(80)),
            Map.entry(EntityType.WARDEN, new MobXP(80)),
            Map.entry(EntityType.WITCH, new MobXP(80)),
            Map.entry(EntityType.WITHER, new MobXP(80)),
            Map.entry(EntityType.WITHER_SKELETON, new MobXP(80)),
            Map.entry(EntityType.WOLF, new MobXP(80)),
            Map.entry(EntityType.ZOMBIE, new MobXP(80)),
            Map.entry(EntityType.ZOMBIE_HORSE, new MobXP(80)),
            Map.entry(EntityType.ZOMBIE_VILLAGER, new MobXP(80)),
            Map.entry(EntityType.ZOMBIFIED_PIGLIN, new MobXP(80))
            );
}
